server:
  port: 3355

spring:
  application:
    name: springcloud-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456


config:
 info: pingan
